#! /bin/csh -f

# This script renames the original file to another name.  It is kept
# around just in case there are multiple check in's or builds in one day.


set myfile = $1

if ( -e ${myfile} ) then

    foreach i ( 1 2 3 4 5 6 7 8 9 )
	if ( ! -e ${myfile}.pass_${i} ) then
	    mv ${myfile} ${myfile}.pass_${i}
	    exit 0
	endif
    end
endif
