cp img-hfr/hfr-mini-px.vm $1
cp img-hfr/hfr-mpls-px.pie $1
cp img-hfr/hfr-mcast-px.pie $1
cp img-hfr/hfr-mgbl-px.pie $1
cp img-asr9k/asr9k-mini-px.vm $1
cp img-asr9k/asr9k-mpls-px.pie $1
cp img-asr9k/asr9k-mcast-px.pie $1
cp img-asr9k/asr9k-mgbl-px.pie $1
cp img-asr9k/asr9k-bng-px.pie $1
