#!/bin/sh -x
if [ -n "$1" -a "$1" = "large" ]; then
  vncserver -geometry 1680x1050
elif [ -n "$1" -a "$1" = "medium" ]; then
  vncserver -geometry 1920x1080
elif [ -n "$1" -a "$1" = "small" ]; then
  vncserver -geometry 2560x1440
else
  vncserver -geometry 1280x960
fi
