cp img-hfr/hfr-mini-px.vm $1
cp img-hfr/hfr-mpls-px.pie $1
cp img-hfr/hfr-mcast-px.pie $1
cp img-hfr/hfr-mgbl-px.pie $1
cp img-asr9k/asr9k-mini-px.vm $1
cp img-asr9k/asr9k-mpls-px.pie $1
cp img-asr9k/asr9k-mcast-px.pie $1
cp img-asr9k/asr9k-mgbl-px.pie $1
cp img-ncs4k/ncs4k-mini-x.iso $1
cp img-ncs4k/ncs4k-full-x.iso $1
cp img-ncs4k/ncs4k-mpls.pkg $1
cp img-ncs4k/ncs4k-mcast.pkg $1
cp img-ncs4k/ncs4k-mgbl.pkg $1
cp img-ncs6k/ncs6k-mini-x.iso $1
cp img-ncs6k/ncs6k-full-x.iso $1
cp img-ncs6k/ncs6k-mpls.pkg $1
cp img-ncs6k/ncs6k-mcast.pkg $1
cp img-ncs6k/ncs6k-mgbl.pkg $1
cp img-xrvr/iosxrv.vmdk $1
cp img-xrvr/xrvr-full-x.vm $1
cp img-ncs1k/*.iso $1
cp img-ncs1k/*.rpm $1
cp img-ncs5k/*.iso $1
cp img-ncs5k/*.rpm $1
cp img-ncs5500/*.iso $1
cp img-ncs5500/*.rpm $1
cp img-xrv9k/*.iso $1
cp img-xrv9k/*.rpm $1
cp img-asr9k/*.iso $1
cp img-asr9k/*.rpm $1
