#! /bin/csh -f


# set obj_all = "obj-4k-rvip obj-4k-svip obj-68-c7000 obj-4k-rsp obj-4k-c7100"

if ( $#argv == 0 ) then
    set yymmdd   = `date +%y%m%d`
else
    set yymmdd   = $1
endif

set tree     = "/cscpv/core_release/ELC/sys"
set obj_dir  = `basename $PWD`
set arch_dir = "/cscpu/core_release/Archives/images.${yymmdd}"

mail -s "START ${obj_dir}" sglee < /dev/null

if ( ! -e ${arch_dir}/${obj_dir} ) then
   mkdir ${arch_dir}/{obj_dir}
endif

cd ${tree}

nice +9  make  MAKEFLAG_J=-j4 GDB_FLAG= BIN_SUFFIX=.${yymmdd} \
	TFTPHOST=potlicker TFTPDIR=${arch_dir}/${obj_dir} \
	production >&! ${arch_dir}/out-${obj_dir}

mail -s "DONE ${obj_dir}" sglee < /dev/null
