#! /bin/csh -x

set day        = `date +%a`
#set yymmdd     = `date +%y%m%d`
set yymmdd     = "960530"
set work_dir   = "/cscpu/sglee"

set tree       = "$work_dir/ELC"
set sun_dir    = "$work_dir/suns"
set symbol_dir = "$work_dir/symbols"
set out        = "$work_dir/Builds/update.${yymmdd}"

set branch   = "ELC_branch"
#set obj_all  = "obj-4k-rvip"
set obj_all  = "obj-4k-rvip obj-4k-svip obj-68-c7000 obj-4k-rsp obj-4k-c7100"


#goto FOO

# ---------------------------------------------------------------------
# Build starts here.
# ---------------------------------------------------------------------
touch $out
cd ${tree}/sys

set now = "`date`"
set pwd = "`pwd`"

cat <<EOF >>& $out
Current directory:  `$PWD`
EOF

foreach prod ( $obj_all )
    cd ${tree}/sys/${prod}
    set now = "`date`"
    set pwd = "`pwd`"
    #cat <<EOF >>& $out

cat <<EOF >>& $out

--------------------------------------------------------------------------------
$now - Building $pwd

EOF
    #nice +10 make -s MAKEFLAG_J=-j4 GDB_FLAG= BIN_SUFFIX=.$yymmdd production >>& $out
    foreach sun ( *.sun )
        cp -pr $sun $sun_dir/suns.${yymmdd}/$sun-$yymmdd
    end
    foreach symbol ( *.symbols )
        cp -pr $symbol $symbol_dir/symbols.${yymmdd}/$symbol-$yymmdd
    end
end

set now = "`date`"
cat <<EOF >>& $out

--------------------------------------------------------------------------------

$now - Build completed.
EOF


# ------------------------------------------------------------------------------
# Add date stamp to the end of all 'vip*' files.
# Move all files into 'boot.DATE' diretory.
# ------------------------------------------------------------------------------
set tftp_path = "/tftpboot/sglee"

#if ( ! -e `rsh dirt ls ${tftp_path}/boot.${yymmdd}` ) then
#    rsh dirt mkdir  ${tftp_path}/boot.${yymmdd}
#endif 

foreach file ( vip21-5 vip2_200-43 )
#    rsh dirt mv  ${tftp_path}/${file}  ${tftp_path}/${file}.${yymmdd}
end

